# 사용할 Kubernetes API 버전
apiVersion: v1
# 생성할 리소스 종류 (Deployment, Service 등)
kind: PersistentVolumeClaim
# 리소스 이름 및 메타데이터 정의 시작
metadata:
# 리소스 이름
  name: {{ .Release.Name }}-efs-pvc
# 리소스의 스펙 정의
spec:
  volumeName: {{ .Release.Name }}-efs-pv
# PVC의 접근 모드 (예: ReadWriteMany)
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
# 사용할 StorageClass 이름
  storageClassName: {{ .Values.storage.storageClassName | default "efs-sc" }}
# CPU 및 메모리 리소스 요청/제한
  resources:
    requests:
      storage: {{ .Values.storage.size | default "5Gi" }}