# 사용할 Kubernetes API 버전
apiVersion: v1
# 생성할 리소스 종류 (Deployment, Service 등)
kind: Secret
# 리소스 이름 및 메타데이터 정의 시작
metadata:
# 리소스 이름
  name: petclinic-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-username: {{ .Values.was.env.DB_USERNAME | quote }}
  db-password: {{ .Values.was.env.DB_PASSWORD | quote }}