# ------------------------------------------------------------
# Service: petclinic-web
# 목적: 외부 또는 클러스터 내부에서 웹 파드에 접근 가능하도록 설정
# ------------------------------------------------------------
# 사용할 Kubernetes API 버전
apiVersion: v1
# 생성할 리소스 종류 (Deployment, Service 등)
kind: Service
# 리소스 이름 및 메타데이터 정의 시작
metadata:
# 리소스 이름
  name: petclinic-web
# 리소스의 스펙 정의
spec:
  type: {{ .Values.web.service.type | default "LoadBalancer" }}  # 외부 노출 시 LoadBalancer로 설정 (기본은 ClusterIP)
  selector:
    app: petclinic-web
# 컨테이너 또는 서비스 포트 정의
  ports:
# 컨테이너 또는 서비스 포트 정의
    - port: {{ .Values.web.port }}         # 클라이언트가 접속할 포트
      targetPort: {{ .Values.web.port }}   # 파드 내부 포트와 동일하게 설정