# 사용할 Kubernetes API 버전
apiVersion: v1
# 생성할 리소스 종류 (Deployment, Service 등)
kind: Service
# 리소스 이름 및 메타데이터 정의 시작
metadata:
# 리소스 이름
  name: petclinic-was  # 백엔드 서비스 이름
# 리소스의 스펙 정의
spec:
  type: {{ .Values.was.service.type | default "ClusterIP" }}
  selector:
    app: petclinic-was  # 파드 선택자
# 컨테이너 또는 서비스 포트 정의
  ports:
    - protocol: TCP
# 컨테이너 또는 서비스 포트 정의
      port: 8080  # 서비스 포트
      targetPort: {{ .Values.was.port }}  # 컨테이너 내부 포트와 매핑