# 사용할 Kubernetes API 버전
apiVersion: storage.k8s.io/v1
# 생성할 리소스 종류 (Deployment, Service 등)
kind: StorageClass
# 리소스 이름 및 메타데이터 정의 시작
metadata:
# 리소스 이름
  name: efs-sc  # PVC에서 참조할 이름
provisioner: efs.csi.aws.com  # Amazon EFS CSI 드라이버
reclaimPolicy: Retain         # PVC 삭제 후에도 EFS 유지
volumeBindingMode: Immediate  # 즉시 바인딩