# 사용할 Kubernetes API 버전
apiVersion: v1
# 생성할 리소스 종류 (Deployment, Service 등)
kind: ConfigMap
# 리소스 이름 및 메타데이터 정의 시작
metadata:
# 리소스 이름
  name: webserver-config
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"
    Listen 80
    ServerName localhost

    # ✅ 필수 MPM 모듈
    LoadModule mpm_event_module modules/mod_mpm_event.so

    # ✅ 프록시 모듈
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so

    # ✅ 추천 기본 모듈
    LoadModule mime_module modules/mod_mime.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule log_config_module modules/mod_log_config.so

    # ✅ 누락된 필수 모듈 (❗️ 반드시 추가)
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule unixd_module modules/mod_unixd.so

    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        AllowOverride None
        Require all granted
    </Directory>

    <VirtualHost *:80>
        ProxyPreserveHost On
        ProxyPass / http://petclinic-was:8080/
        ProxyPassReverse / http://petclinic-was:8080/
    </VirtualHost>

    ErrorLog /proc/self/fd/2
    LogLevel warn